apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-apps
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/system/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-infra
  timeout: 2m
  validation: client
