apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    admin-password: AgC3EXAMPLEENCRYPTEDDATAo4Uud5==  # <-- Replace with real encryption using kubeseal
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: Opaque
