apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dc11b

resources:
- ../../../../base/coredns

patches:
- path: remove-clusterip-patch.yaml
  target:
    kind: Service
    name: kube-dns
- path: application-patch.yaml
  target:
    kind: Application
    name: coredns-dc11b
