loki:
  auth_enabled: false  # Optional if not using multi-tenancy
  commonConfig:
    replication_factor: 3
  storage:
    type: filesystem  # Or 's3', 'gcs' in production
  schemaConfig:
    configs:
      - from: "2022-01-01"
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

  compactor:
    enabled: true
    shared_store: filesystem
    retention_enabled: true
    retention_delete_delay: 2h
    retention_period: 168h  # 7 days

  limits_config:
    retention_period: 168h
    max_query_parallelism: 32
    max_query_length: 168h
    reject_old_samples: true
    reject_old_samples_max_age: 168h

write:
  replicas: 2
read:
  replicas: 2
backend:
  replicas: 2
gateway:
  enabled: true
  replicas: 2
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: logs.emodo.io
        paths:
          - /
    tls:
      - secretName: loki-tls

monitoring:
  dashboards:
    enabled: true
  rules:
    enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus
  selfMonitoring:
    enabled: true
    lokiCanary:
      enabled: true

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 2Gi

tolerations:
  - key: "node-role.kubernetes.io/control-plan
