resources:
  - namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: core
    repo: https://neuvector.github.io/neuvector-helm/
    version: 2.8.6
    releaseName: neuvector
    namespace: neuvector
    valuesFile: values.yaml
