apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# Reference the base Grafana configuration
resources:
  - ../../../../base/grafana/namespace.yaml
  - ../../../../base/grafana/serviceaccount.yaml
  - ../../../../base/grafana/configmap.yaml
  - ../../../../base/grafana/service.yaml
  - ../../../../base/grafana/deployment.yaml
  - ../../../../base/grafana/hpa.yaml

# Patches for various resources
patches:
  # Remove the PVC resource
  - target:
      kind: PersistentVolumeClaim
      name: grafana-storage
    patch: |-
      - op: remove
        path: /metadata/name
        value: grafana-storage

  # Patch the Deployment to use emptyDir and update security context
  - path: json-patch.yaml
    target:
      kind: Deployment
      name: grafana

  # Patch the HPA to adjust scaling for dc11a
  - target:
      kind: HorizontalPodAutoscaler
      name: grafana
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3

# Labels for all resources
labels:
  - pairs:
      app.kubernetes.io/environment: prod
      app.kubernetes.io/cluster: dc11a

# Namespace
namespace: monitoring

# Images
images:
  - name: grafana/grafana
    newName: grafana/grafana
    newTag: 10.4.2

# Common annotations
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "-1"
