apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
  labels:
    app.kubernetes.io/cluster: dc11a
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-system
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
