apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    api-token: AgC3EXAMPLEENCRYPTEDDATAo4Uud5==  # Replace with real encryption
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
