apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources
resources:
  - ../../../../base/monitoring
  - network-policy.yaml
  - pdb.yaml
  - service-monitor.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/part-of: monitoring
  app.kubernetes.io/environment: prod
  topology.kubernetes.io/region: us-west-2
  topology.kubernetes.io/zone: us-west-2a
  cluster: dc11a

# Name prefix for all resources
namePrefix: ""

# Namespace to deploy resources to
namespace: monitoring

# ConfigMap generator for monitoring configuration
configMapGenerator:
  - name: monitoring-config
    literals:
      - SCRAPE_INTERVAL=30s
      - EVALUATION_INTERVAL=30s
      - RETENTION=15d

# Secret generator for sensitive configuration
secretGenerator:
  - name: monitoring-secrets
    literals:
      - GRAFANA_ADMIN_PASSWORD=$(echo -n "${GRAFANA_ADMIN_PASSWORD}" | base64)
    type: Opaque

# Images to use for components
images:
  - name: prom/prometheus
    newTag: v2.47.0
  - name: grafana/grafana
    newTag: 10.2.0
  - name: prom/alertmanager
    newTag: v0.26.0
  - name: prom/node-exporter
    newTag: v1.6.1
  - name: prom/blackbox-exporter
    newTag: v0.24.0
  - name: jimmidyson/configmap-reload
    newTag: v0.10.0

# Patches for monitoring components
patches:
  # Security context for all pods
  - target:
      kind: Deployment
      name: ".*"
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext
        value:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          seccompProfile:
            type: RuntimeDefault
  
  # Container security context
  - target:
      kind: Deployment
      name: ".*"
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/securityContext
        value:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault

  # Resource limits
  - target:
      kind: Deployment
      name: "prometheus-operator"
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 1Gi

  # Node affinity and tolerations
  - target:
      kind: Deployment
      name: ".*"
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/worker
                  operator: In
                  values: ["true"]
                - key: topology.kubernetes.io/zone
                  operator: In
                  values: ["us-west-2a"]
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values: ["prometheus-operator"]
                topologyKey: kubernetes.io/hostname

  # Pod topology spread constraints
  - target:
      kind: Deployment
      name: ".*"
    patch: |-
      - op: add
        path: /spec/template/spec/topologySpreadConstraints
        value:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfied: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/part-of: monitoring
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfied: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/part-of: monitoring

# List of transformations to apply
transformerConfigs:
  - default-pod-annotations.yaml
  - default-pod-labels.yaml
