apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/environment: prod
    topology.kubernetes.io/region: us-west-2
    topology.kubernetes.io/zone: us-west-2a
    cluster: dc11a
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: monitoring
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/environment: prod
    topology.kubernetes.io/region: us-west-2
    topology.kubernetes.io/zone: us-west-2a
    cluster: dc11a
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: monitoring
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/environment: prod
    topology.kubernetes.io/region: us-west-2
    topology.kubernetes.io/zone: us-west-2a
    cluster: dc11a
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/part-of: monitoring
