apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-self
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring-self
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/environment: prod
    topology.kubernetes.io/region: us-west-2
    topology.kubernetes.io/zone: us-west-2a
    cluster: dc11a
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: monitoring
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: web
    interval: 30s
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: '(container_cpu_usage_seconds_total|container_memory_working_set_bytes)'
      action: keep

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: monitoring-self-rules
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/environment: prod
    topology.kubernetes.io/region: us-west-2
    topology.kubernetes.io/zone: us-west-2a
    cluster: dc11a
spec:
  groups:
  - name: monitoring-self
    rules:
    - alert: PrometheusDown
      expr: up{job="prometheus"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Prometheus is down
        description: Prometheus {{ $labels.instance }} is down

    - alert: PrometheusConfigurationReloadFailed
      expr: prometheus_config_last_reload_successful{job="prometheus"} == 0
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: Prometheus configuration reload failed
        description: Prometheus {{ $labels.instance }} configuration reload failed

    - alert: PrometheusTSDBWALCorruptions
      expr: prometheus_tsdb_wal_corruptions_total{job="prometheus"} > 0
      labels:
        severity: warning
      annotations:
        summary: Prometheus WAL corruptions detected
        description: Prometheus {{ $labels.instance }} has {{ $value }} WAL corruptions

    - alert: PrometheusTSDBCompactionsFailing
      expr: increase(prometheus_tsdb_compactions_failed_total{job="prometheus"}[1h]) > 0
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: Prometheus compactions are failing
        description: Prometheus {{ $labels.instance }} has {{ $value }} compaction failures in the last hour
