server:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
  metrics:
    enabled: true
applicationController:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
