apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: longhorn-webhook-validator
  annotations:
    kustomize.toolkit.fluxcd.io/checksum: ""
webhooks:
- name: validator.longhorn.io
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Fail
  matchPolicy: Equivalent
  timeoutSeconds: 10
  clientConfig:
    service:
      name: longhorn-longhorn-admission-webhook-dc11a
      namespace: longhorn-system
      path: /v1/webhook/validation
      port: 9502
  rules:
  - apiGroups: ["longhorn.io"]
    apiVersions: ["v1beta2"]
    operations: ["CREATE", "UPDATE"]
    resources: ["volumes", "nodes", "settings", "recurringjobs", "backingimages", "orphans", "snapshots", "supportbundles", "systembackups", "systemrestores", "volumeattachments", "engines", "replicas", "instancemanagers"]
    scope: "Namespaced"
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: longhorn-webhook-mutator
  annotations:
    kustomize.toolkit.fluxcd.io/checksum: ""
webhooks:
- name: mutator.longhorn.io
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Fail
  matchPolicy: Equivalent
  reinvocationPolicy: Never
  timeoutSeconds: 10
  clientConfig:
    service:
      name: longhorn-longhorn-admission-webhook-dc11a
      namespace: longhorn-system
      path: /v1/webhook/mutation
      port: 9502
  rules:
  - apiGroups: ["longhorn.io"]
    apiVersions: ["v1beta2"]
    operations: ["CREATE", "UPDATE"]
    resources: ["backups", "backingimages", "backingimagemanagers", "backingimagedatasources", "nodes", "volumes", "engines", "recurringjobs", "engineimages", "orphans", "sharemanagers", "backupvolumes", "snapshots", "replicas", "supportbundles", "systembackups", "volumeattachments", "instancemanagers", "backupbackingimages"]
    scope: "Namespaced"
