apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-gitops-dc11a
  namespace: argocd
  labels:
    cluster: dc11a
    environment: prod
    app.kubernetes.io/name: root-gitops
    app.kubernetes.io/instance: root-gitops-dc11a
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/instance: root-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/vietcgi/infra.git
    targetRevision: main
    path: apps/gitops/argocd/prod/dc11a
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
