apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sealed-secrets
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/component: controller
spec:
  secretName: sealed-secrets-tls
  duration: 8760h  # 1 year
  renewBefore: 720h  # 30 days
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  dnsNames:
  - sealed-secrets.kube-system.svc
  - sealed-secrets.kube-system.svc.cluster.local
  issuerRef:
    name: vault-issuer  # Replace with your issuer
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
  uris:
  - spiffe://cluster.local/ns/kube-system/sa/sealed-secrets
---
# Fallback self-signed certificate if cert-manager is not available
apiVersion: v1
kind: Secret
metadata:
  name: sealed-secrets-tls
  namespace: kube-system
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: kubernetes.io/tls
data:
  # These are placeholder values that will be replaced by the actual certificate
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE...
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIE...
    -----END RSA PRIVATE KEY-----
