apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sealed-secrets
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: monitoring
    prometheus: k8s
    role: alert-rules
spec:
  groups:
  - name: sealed-secrets.rules
    rules:
    - alert: SealedSecretsCertificateExpiry
      expr: sealed_secrets_controller_cert_expires_in_seconds < 2592000  # 30 days
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: Sealed Secrets certificate expiring soon
        description: |
          The Sealed Secrets certificate for {{ $labels.namespace }}/{{ $labels.name }}
          will expire in {{ $value | humanizeDuration }}.
          Please rotate the certificate.

    - alert: SealedSecretsKeyRotationFailed
      expr: increase(sealed_secrets_controller_key_rotation_errors_total[1h]) > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Sealed Secrets key rotation failed
        description: |
          The Sealed Secrets controller failed to rotate the encryption key.
          Error: {{ $labels.error }}

    - alert: SealedSecretsUnsealErrorRate
      expr: rate(sealed_secrets_controller_unseal_errors_total[5m]) > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High rate of Sealed Secrets unseal errors
        description: |
          There are {{ $value }} unseal errors in the last 5 minutes.
          This may indicate a problem with the encryption key.

    - alert: SealedSecretsControllerDown
      expr: up{job="sealed-secrets"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Sealed Secrets controller is down
        description: |
          The Sealed Secrets controller has been down for more than 5 minutes.
