apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io/background
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/instance: argocd
    environment: ENV_PLACEHOLDER  # Will be replaced by kustomize
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.0.17  # Match the chart version being used in bootstrap
    helm:
      releaseName: argocd
      values: |
        installCRDs: true
        networkPolicy:
          create: false
        controller:
          replicas: 2
          priorityClassName: system-cluster-critical
          metrics:
            enabled: true
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
        server:
          replicas: 2
          service:
            type: ClusterIP
            servicePortHttp: 80
            servicePortHttps: 443
            targetPortHttp: 8080
            targetPortHttps: 8080
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - argocd.emodo.io
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            tls:
              - hosts:
                  - argocd.emodo.io
                secretName: argocd-tls
          livenessProbe:
            httpGet:
              path: /healthz?full=true
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          metrics:
            enabled: true
          priorityClassName: system-cluster-critical
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: argocd-application-controller
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      name: argocd-application-controller
      jsonPointers:
        - /spec/replicas
