apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/coredns
  - hpa.yaml

patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: coredns
