apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: system-apps
  namespace: fleet-default
spec:
  repo: https://github.com/vietcgi/infractl.git
  branch: main
  paths:
    - apps/system/overlays/prod
  targetNamespace: system-apps
  helm:
    releaseName: system-stack
