apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vietcgi/infra.git
    targetRevision: dev
    path: apps/gitops/argocd/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
