apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/part-of: kube-system
    app.kubernetes.io/component: monitoring
data:
  grafana.ini: |
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [server]
    http_port = 3000
    domain = localhost
    root_url = %(protocol)s://%(domain)s/
    serve_from_sub_path = false
    enable_gzip = true

    [database]
    type = sqlite3

    [security]
    admin_user = admin
    admin_password = admin  # Change this in production
    secret_key = 
    disable_initial_admin_creation = false
    disable_gravatar = true
    cookie_secure = true
    cookie_samesite = lax
    strict_transport_security = true
    strict_transport_security_max_age_seconds = 31536000
    strict_transport_security_preload = true
    strict_transport_security_subdomains = true
    x_frame_options = deny
    x_content_type_options = true
    x_xss_protection = true

    [users]
    allow_sign_up = false
    auto_assign_org = true
    auto_assign_org_role = Viewer
    verify_email_enabled = true

    [auth]
    disable_login_form = false
    disable_signout_menu = false
    oauth_auto_login = false
    signout_redirect_url = /login

    [auth.anonymous]
    enabled = false

    [auth.basic]
    enabled = false

    [auth.ldap]
    enabled = false

    [auth.proxy]
    enabled = false

    [auth.github]
    enabled = false

    [auth.gitlab]
    enabled = false

    [auth.google]
    enabled = false

    [auth.generic_oauth]
    enabled = false

    [auth.okta]
    enabled = false

    [smtp]
    enabled = false

    [unified_alerting]
    enabled = true
