apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: grafana
chartName: grafana/grafana
chartVersion: "7.2.0"
chartRepo: https://grafana.github.io/helm-charts
releaseName: grafana
releaseNamespace: monitoring
values:
  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
  podSecurityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
    runAsNonRoot: true
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    type: pvc
    enabled: true
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    size: 10Gi
