apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    environment: dev
spec:
  source:
    helm:
      values: |
        server:
          ingress:
            hosts:
              - argocd.dev.emodo.io
            tls:
              - hosts:
                  - argocd.dev.emodo.io
                secretName: argocd-tls
