apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

# Include the base resources
resources:
  - ../../../base/argocd

# Apply patches
patches:
  - path: application-patch.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: argocd
