apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

<<<<<<< HEAD
resources:
  - ../../../../base/argocd
  # - ../../../../base/monitoring  # Uncomment/add as needed
  - ../../../../base/argocd-app.yaml

components:
  - ../../../../components/argocd/cluster

configMapGenerator:
  - name: cluster-config
    literals:
      - CLUSTER_NAME=dc11a
      - ENVIRONMENT=prod
      - INGRESS_HOST=argocd.dc11a.prod.emodo.io

labels:
  - pairs:
      cluster: dc11a
      environment: prod

patchesStrategicMerge:
  - argocd-values-patch.yaml 
=======
# Disable load restrictions to allow referencing files outside the overlay
configurations:
  - kustomizeconfig.yaml

resources:
  - grafana
  - grafana-simple/
  - argocd/
  - monitoring/
  - metrics-server/
  - longhorn/
  - coredns/
  - sealed-secrets/
  - rancher/
  - prometheus-operator-crds/
  - prometheus/
  - nodelocaldns/
  - nginx-ingress/
  - neuvector/
  - cilium/
  - cert-manager-crds/
  - alertmanager/
  - loki/
  - cert-manager/ 
>>>>>>> parent of d2ac4a0 (testing)
