apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

# Add the Longhorn Helm repository
helmCharts:
- name: longhorn
  repo: https://charts.longhorn.io
  version: 1.9.0
  releaseName: longhorn
  namespace: longhorn-system
  valuesFile: values.yaml
  includeCRDs: true
  skipHooks: false

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: longhorn
  app.kubernetes.io/instance: longhorn
  app.kubernetes.io/component: storage
  app.kubernetes.io/part-of: longhorn
