apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: kube-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: prometheus-server
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 2Gi
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 1
          periodSeconds: 180
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
      stabilizationWindowSeconds: 0
